apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: mlops-loan-cluster
  region: ap-south-1

managedNodeGroups:
  - name: mlops-workers
    instanceType: t3.small
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
    volumeSize: 30