apiVersion: apps/v1
kind: Deployment

metadata:
  name: loan-approval-api

spec:
  replicas: 2

  selector:
    matchLabels:
      app: loan-approval-api

  template:
    metadata:
      labels:
        app: loan-approval-api

    spec:
      containers:
        - name: loan-approval-api

          image: 516938789431.dkr.ecr.ap-south-1.amazonaws.com/loan-approval-api:1.1

          ports:
            - containerPort: 8000

          env:
            - name: MODEL_NAME
              valueFrom:
                configMapKeyRef:
                  name: loan-approval-config
                  key: MODEL_NAME

            - name: MODEL_VERSION
              valueFrom:
                configMapKeyRef:
                  name: loan-approval-config
                  key: MODEL_VERSION  